call bin\CLAMI.bat -f data/AEEEM-eclipse.arff -l bug -p 1 >  CLA_AEEEM-eclipse.csv
call bin\CLAMI.bat -f data/AEEEM-equinox.arff -l bug -p 1 >  CLA_AEEEM-equinox.csv
call bin\CLAMI.bat -f data/AEEEM-lucene.arff -l bug -p 1 >  CLA_AEEEM-lucene.csv
call bin\CLAMI.bat -f data/AEEEM-mylyn.arff -l bug -p 1 >  CLA_AEEEM-mylyn.csv
call bin\CLAMI.bat -f data/AEEEM-pde.arff -l bug -p 1 >  CLA_AEEEM-pde.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-ant-1.3.arff -l bug -p 1 > CLA_ALLJURECZKO-ant-1.3.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-ant-1.4.arff -l bug -p 1 > CLA_ALLJURECZKO-ant-1.4.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-ant-1.5.arff -l bug -p 1 > CLA_ALLJURECZKO-ant-1.5.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-ant-1.6.arff -l bug -p 1 > CLA_ALLJURECZKO-ant-1.6.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-ant-1.7.arff -l bug -p 1 > CLA_ALLJURECZKO-ant-1.7.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-arc.arff -l bug -p 1 > CLA_ALLJURECZKO-arc.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-berek.arff -l bug -p 1 > CLA_ALLJURECZKO-berek.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-camel-1.0.arff -l bug -p 1 > CLA_ALLJURECZKO-camel-1.0.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-camel-1.2.arff -l bug -p 1 > CLA_ALLJURECZKO-camel-1.2.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-camel-1.4.arff -l bug -p 1 > CLA_ALLJURECZKO-camel-1.4.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-camel-1.6.arff -l bug -p 1 > CLA_ALLJURECZKO-camel-1.6.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-ckjm.arff -l bug -p 1 > CLA_ALLJURECZKO-ckjm.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-e-learning.arff -l bug -p 1 > CLA_ALLJURECZKO-e-learning.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-forrest-0.7.arff -l bug -p 1 > CLA_ALLJURECZKO-forrest-0.7.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-ivy-1.1.arff -l bug -p 1 > CLA_ALLJURECZKO-ivy-1.1.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-ivy-1.4.arff -l bug -p 1 > CLA_ALLJURECZKO-ivy-1.4.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-ivy-2.0.arff -l bug -p 1 > CLA_ALLJURECZKO-ivy-2.0.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-jedit-3.2.arff -l bug -p 1 > CLA_ALLJURECZKO-jedit-3.2.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-jedit-4.0.arff -l bug -p 1 > CLA_ALLJURECZKO-jedit-4.0.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-jedit-4.1.arff -l bug -p 1 > CLA_ALLJURECZKO-jedit-4.1.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-jedit-4.2.arff -l bug -p 1 > CLA_ALLJURECZKO-jedit-4.2.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-jedit-4.3.arff -l bug -p 1 > CLA_ALLJURECZKO-jedit-4.3.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-kalkulator.arff -l bug -p 1 > CLA_ALLJURECZKO-kalkulator.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-log4j-1.0.arff -l bug -p 1 > CLA_ALLJURECZKO-log4j-1.0.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-log4j-1.1.arff -l bug -p 1 > CLA_ALLJURECZKO-log4j-1.1.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-log4j-1.2.arff -l bug -p 1 > CLA_ALLJURECZKO-log4j-1.2.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-lucene-2.0.arff -l bug -p 1 > CLA_ALLJURECZKO-lucene-2.0.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-lucene-2.2.arff -l bug -p 1 > CLA_ALLJURECZKO-lucene-2.2.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-lucene-2.4.arff -l bug -p 1 > CLA_ALLJURECZKO-lucene-2.4.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-nieruchomosci.arff -l bug -p 1 > CLA_ALLJURECZKO-nieruchomosci.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-pbeans1.arff -l bug -p 1 > CLA_ALLJURECZKO-pbeans1.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-pbeans2.arff -l bug -p 1 > CLA_ALLJURECZKO-pbeans2.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-pdftranslator.arff -l bug -p 1 > CLA_ALLJURECZKO-pdftranslator.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-poi-1.5.arff -l bug -p 1 > CLA_ALLJURECZKO-poi-1.5.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-poi-2.0.arff -l bug -p 1 > CLA_ALLJURECZKO-poi-2.0.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-poi-2.5.arff -l bug -p 1 > CLA_ALLJURECZKO-poi-2.5.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-poi-3.0.arff -l bug -p 1 > CLA_ALLJURECZKO-poi-3.0.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-redaktor.arff -l bug -p 1 > CLA_ALLJURECZKO-redaktor.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-serapion.arff -l bug -p 1 > CLA_ALLJURECZKO-serapion.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-skarbonka.arff -l bug -p 1 > CLA_ALLJURECZKO-skarbonka.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-sklebagd.arff -l bug -p 1 > CLA_ALLJURECZKO-sklebagd.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-synapse-1.0.arff -l bug -p 1 > CLA_ALLJURECZKO-synapse-1.0.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-synapse-1.1.arff -l bug -p 1 > CLA_ALLJURECZKO-synapse-1.1.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-synapse-1.2.arff -l bug -p 1 > CLA_ALLJURECZKO-synapse-1.2.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-systemdata.arff -l bug -p 1 > CLA_ALLJURECZKO-systemdata.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-szybkafucha.arff -l bug -p 1 > CLA_ALLJURECZKO-szybkafucha.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-termoproject.arff -l bug -p 1 > CLA_ALLJURECZKO-termoproject.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-tomcat.arff -l bug -p 1 > CLA_ALLJURECZKO-tomcat.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-velocity-1.4.arff -l bug -p 1 > CLA_ALLJURECZKO-velocity-1.4.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-velocity-1.5.arff -l bug -p 1 > CLA_ALLJURECZKO-velocity-1.5.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-velocity-1.6.arff -l bug -p 1 > CLA_ALLJURECZKO-velocity-1.6.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-workflow.arff -l bug -p 1 > CLA_ALLJURECZKO-workflow.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-wspomaganiepi.arff -l bug -p 1 > CLA_ALLJURECZKO-wspomaganiepi.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-xalan-2.4.arff -l bug -p 1 > CLA_ALLJURECZKO-xalan-2.4.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-xalan-2.5.arff -l bug -p 1 > CLA_ALLJURECZKO-xalan-2.5.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-xalan-2.6.arff -l bug -p 1 > CLA_ALLJURECZKO-xalan-2.6.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-xalan-2.7.arff -l bug -p 1 > CLA_ALLJURECZKO-xalan-2.7.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-xerces-1.2.arff -l bug -p 1 > CLA_ALLJURECZKO-xerces-1.2.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-xerces-1.3.arff -l bug -p 1 > CLA_ALLJURECZKO-xerces-1.3.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-xerces-1.4.arff -l bug -p 1 > CLA_ALLJURECZKO-xerces-1.4.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-xerces-1.0.arff -l bug -p 1 > CLA_ALLJURECZKO-xerces-1.0.csv
call bin\CLAMI.bat -f data/ALLJURECZKO-zuzel.arff -l bug -p 1 > CLA_ALLJURECZKO-zuzel.csv
call bin\CLAMI.bat -f data/MDP-CM1.arff -l bug -p 1 > CLA_MDP-CM1.csv
call bin\CLAMI.bat -f data/MDP-JM1.arff -l bug -p 1 > CLA_MDP-JM1.csv
call bin\CLAMI.bat -f data/MDP-KC1.arff -l bug -p 1 > CLA_MDP-KC1.csv
call bin\CLAMI.bat -f data/MDP-KC3.arff -l bug -p 1 > CLA_MDP-KC3.csv
call bin\CLAMI.bat -f data/MDP-MC1.arff -l bug -p 1 > CLA_MDP-MC1.csv
call bin\CLAMI.bat -f data/MDP-MC2.arff -l bug -p 1 > CLA_MDP-MC2.csv
call bin\CLAMI.bat -f data/MDP-MW1.arff -l bug -p 1 > CLA_MDP-MW1.csv
call bin\CLAMI.bat -f data/MDP-PC1.arff -l bug -p 1 > CLA_MDP-PC1.csv
call bin\CLAMI.bat -f data/MDP-PC2.arff -l bug -p 1 > CLA_MDP-PC2.csv
call bin\CLAMI.bat -f data/MDP-PC3.arff -l bug -p 1 > CLA_MDP-PC3.csv
call bin\CLAMI.bat -f data/MDP-PC4.arff -l bug -p 1 > CLA_MDP-PC4.csv
call bin\CLAMI.bat -f data/MDP-PC5.arff -l bug -p 1 > CLA_MDP-PC5.csv
call bin\CLAMI.bat -f data/NETGENE-httpclient.arff -l bug -p 1 > CLA_NETGENE-httpclient.csv
call bin\CLAMI.bat -f data/NETGENE-jackrabbit.arff -l bug -p 1 > CLA_NETGENE-jackrabbit.csv
call bin\CLAMI.bat -f data/NETGENE-lucene.arff -l bug -p 1 > CLA_NETGENE-lucene.csv
call bin\CLAMI.bat -f data/NETGENE-rhino.arff -l bug -p 1 > CLA_NETGENE-rhino.csv
call bin\CLAMI.bat -f data/RELINK-Apache2.0.arff -l bug -p 1 > CLA_RELINK-Apache2.0.csv
call bin\CLAMI.bat -f data/RELINK-openintents.arff -l bug -p 1 > CLA_RELINK-openintents.csv
call bin\CLAMI.bat -f data/RELINK-zxing1.6.arff -l bug -p 1 > CLA_RELINK-zxing1.6.csv