call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt
call timecmd.bat batch.bat .>> time_log_CLA.txt